### ISSUE TITLE
Add basic functionality to add package from JSON

### ISSUE THREAD

**Issue by olegmoz** [artipie/composer-adapter#1]
Here is minimal package JSON as described at https://getcomposer.org/doc/05-repositories.md
```
{
    "name": "smarty/smarty",
    "version": "3.1.7",
    "dist": {
        "url": "https://www.smarty.net/files/Smarty-3.1.7.zip",
        "type": "zip"
    }
}
```

It should be added to package versions list to serve package info request (see https://packagist.org/apidoc):

```
GET https://repo.packagist.org/p/[vendor]/[package].json

{
  "packages": {
    "[vendor]/[package]": {
      "[version1]": {
        "name": "[vendor]/[package],
        "description": [description],
        // ...
      },
      "[version2]": {
        // ...
      }
      // ...
    }
  }
}
```

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/composer-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/composer-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#1` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
