### ISSUE TITLE
Brief project description in README with doc links

### ISSUE THREAD

**Issue by olegmoz** [artipie/composer-adapter#2]

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/composer-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/composer-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#2` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
