### ISSUE TITLE
HTTP support for adding package as ZIP archive

### ISSUE THREAD

**Issue by olegmoz** [artipie/composer-adapter#23]
There is no generic way to add a package via CLI, so every repository provides it's own way. We would use for a start the way used in some other repos: making a PUT request to repository root with package content ZIP in request body.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#23` is not assigned, can't get performer

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#23` is not assigned, can't get performer
