### ISSUE TITLE
HTTP support for getting package metadata

### ISSUE THREAD

**Issue by olegmoz** [artipie/composer-adapter#24]
API docs: https://packagist.org/apidoc

Package metadata should be served by request:
```
GET https://repo.packagist.org/p/[vendor]/[package].json
```
In the following format:
```
{
  "packages": {
    "[vendor]/[package]": {
      "[version1]": {
        "name": "[vendor]/[package],
        "description": [description],
        // ...
      },
      "[version2]": {
        // ...
      }
      // ...
    }
  }
}
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#24` is not assigned, can't get performer
