### ISSUE TITLE
Upgrade ASTO storage to 0.15+

### ISSUE THREAD

**Issue by olegmoz** [artipie/composer-adapter#41]

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#41` is not assigned, can't get performer

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by olegmoz** [comment]
@g4s8 could you please look into this? Cannot understand what has gone wrong with release

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@olegmoz looks like rultor doesn't have `composer` tool which is used by integration tests, should be fixed by https://github.com/artipie/composer-adapter/commit/44a510330beab56359e4642cd837052d56c8e9a9
