### ISSUE TITLE
Remove base path support feature 

### ISSUE THREAD

**Issue by olegmoz** [artipie/composer-adapter#64]
Base path support is not required in PHP Composer. In Artipie it should be established on upper level

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2`

**Comment by olegmoz** [comment]
@yegor256 could you please touch `.rultor.yml` in order to allow release in this repo?

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#64` is not assigned, can't get performer

**Comment by yegor256** [comment]
@olegmoz done in d660c1d

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2`

**Comment by olegmoz** [comment]
@yegor256 thanks for touching the file, but there is still problem with creating release: `.rultor.yml in yegor256/home doesn't allow artipie/composer-adapter to use its assets (there are 108 friends), see http://doc.rultor.com/reference.html#assets`

**Comment by yegor256** [comment]
@olegmoz this was the problem: 5ea758b

**Comment by olegmoz** [comment]
@yegor256 thanks!

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2`

**Comment by olegmoz** [comment]
@yegor256 release still fails with the following error: `.rultor.yml file must be present in root directory of artipie/artipie-keys, see http://doc.rultor.com/reference.html#assets`, please look into this

**Comment by olegmoz** [comment]
@yegor256 please help with `.rultor.yml`, our progress is blocked because of this issue

**Comment by yegor256** [comment]
@olegmoz try again after 2584447

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2`
