### ISSUE TITLE
Non-blocking repository implementation

### ISSUE THREAD

**Issue by olegmoz** [artipie/composer-adapter#66]
Right now PHP composer implementation is blocking calling threads on performing I/O operations. This might cause troubles in Vert.x and fork/join thread pools

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#69](https://github.com/artipie/composer-adapter/issues/69) is still not solved.

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#69](https://github.com/artipie/composer-adapter/issues/69) is solved here.

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#66` is not assigned, can't get performer
