### ISSUE TITLE
HTTP endpoints should not interact with Storage

### ISSUE THREAD

**Issue by olegmoz** [artipie/composer-adapter#67]
HTTP endpoints should not interact with `Storage` directly. All operations should go through `Repository` abstraction. This way repository could be implemented as local storage interacting with ASTO `Storage` or as proxy that uses remote server to retrieve data

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#67` is not assigned, can't get performer
