### ISSUE TITLE
RepositoryHttpIT.java:59-62: Enable repository...

### ISSUE THREAD

**Issue by 0pdd** [artipie/composer-adapter#69]
The puzzle `66-9f8b5d33` from #66 has to be resolved: 

https://github.com/artipie/composer-adapter/blob/00e9aca3058c90af101a24ae8f975ef7f79f9be6/src/test/java/com/artipie/composer/RepositoryHttpIT.java#L59-L62

The puzzle was created by @olegmoz on 18-Jan-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#69` is not assigned, can't get performer
