### ISSUE TITLE
Authentication and authorization

### ISSUE THREAD

**Issue by olegmoz** [artipie/composer-adapter#71]
PHP composer does not have auth support yet and all operations are available to all users. It should have authentication support and require `read` and `write` permissions for it's endpoints

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#71` is not assigned, can't get performer
