### ISSUE TITLE
Extract Repository interface

### ISSUE THREAD

**Issue by olegmoz** [artipie/composer-adapter#75]
To support proxy PHP composer repository in future HTTP layer should depend on interface. Right now it depends on `Repository` class which is implementation of PHP composer repository storing data in ASTO storage.

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3.1`

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#75` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3.2`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3.3`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3.4`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3.6`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.3.7`
