### ISSUE TITLE
Composer - remote repository

### ISSUE THREAD

**Issue by ZHRen** [artipie/composer-adapter#77]
Please support remote repository in composer-adapter for proxying packagist.org. 

Progress:
- [x] basic implementation 
- [x] unit tests for added classes
- [x] IT for installation from remote
- [x] IT for installation from local

Caching of combined from local and remote files
- [x] class for validate cached item by checking time of saving on expiration `CacheTimeControl`
- [x] implementation of `Cache` interface for this repository
- [x] tests for `ComposerStorageCache`
- [ ] IT for installation from cache

**Comment by genryxy** [comment]
@g4s8 could you please release `0.4` version

**Comment by genryxy** [comment]
@rultor release, tag=0.4

**Comment by g4s8** [comment]
@rultor release, tag=`0.4`

**Comment by g4s8** [comment]
@genryxy could you please add yourself into the list of users with release permissions in `rultor.yml` config?

**Comment by g4s8** [comment]
@rultor release, tag=`0.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.4`

**Comment by genryxy** [comment]
@rultor release, tag=0.4

**Comment by genryxy** [comment]
@g4s8 could you please take a look

**Comment by g4s8** [comment]
@rultor release, tag=`0.4`

**Comment by g4s8** [comment]
@rultor stop

**Comment by yegor256** [comment]
@g4s8 done

**Comment by g4s8** [comment]
@rultor release, tag=`1.0`

**Comment by g4s8** [comment]
@genryxy can you please check build error?

**Comment by 0pdd** [comment]
@ZHRen 2 puzzles [#111](https://github.com/artipie/composer-adapter/issues/111), [#112](https://github.com/artipie/composer-adapter/issues/112) are still not solved.

**Comment by genryxy** [comment]
@rultor release, tag=`1.0`

**Comment by genryxy** [comment]
@rultor release, tag=`1.0`

**Comment by genryxy** [comment]
@rultor release, tag=`1.0`

**Comment by genryxy** [comment]
@rultor release, tag=`1.0`

**Comment by g4s8** [comment]
@genryxy it's released successfully but server returned error code, see: https://repo1.maven.org/maven2/com/artipie/composer-adapter/1.0/

**Comment by genryxy** [comment]
@g4s8 ooh, thanks, got it

**Comment by 0pdd** [comment]
@ZHRen 2 puzzles [#unknown](), [#unknown]() are still not solved.
