### ISSUE TITLE
Use Testcontainers for IT cases

### ISSUE THREAD

**Issue by genryxy** [artipie/composer-adapter#78]
Let's use `Testcontainers` for IT cases, since then it is not necessary a pre-installed environment on the machine.

**Comment by 0pdd** [comment]
@genryxy the puzzle [#80](https://github.com/artipie/composer-adapter/issues/80) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#78` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@genryxy the puzzle [#120](https://github.com/artipie/composer-adapter/issues/120) is still not solved.

**Comment by 0pdd** [comment]
@genryxy the puzzle [#unknown]() is still not solved; solved: [#120](https://github.com/artipie/composer-adapter/issues/120).
