### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by genryxy** [artipie/composer-adapter#84]
The main features that the composer-adapter should support:
- [x] HTTP support for adding package as `composer.json`
- [x]  HTTP support for getting package metadata
- [x] HTTP support for adding package as ZIP archive #23 
- [ ] Remote repository #77
- [ ] Support no-version packages #83

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#84` is not assigned, can't get performer
