### ISSUE TITLE
Use Content instead of ByteSource

### ISSUE THREAD

**Issue by genryxy** [artipie/composer-adapter#85]
Let's use custom wrapper `Content` instead of `ByteSource` because other adapters use this class and there many useful wrappers to work with instances of this type. Besides, `Content` is written in reactive style

**Comment by 0crat** [comment]
You @genryxy[/z](https://www.0crat.com/u/genryxy) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#85` is not assigned, can't get performer
