### ISSUE TITLE
Composer - local repository

### ISSUE THREAD

**Issue by g4s8** [artipie/composer-adapter#96]
The main features that the composer-adapter should support:
- [x] HTTP support for adding package as `composer.json`
- [x]  HTTP support for getting package metadata
- [x] HTTP support for adding package as ZIP archive #23 
- [x] Support no-version packages #83

**Comment by kirill-h5i** [comment]
@genryxy all sub-tasks were done, can we close and release?

**Comment by genryxy** [comment]
@g4s8 @kirill-h5i yeah, I think this issue could be closed and we can release

**Comment by g4s8** [comment]
@rultor release, tag=`0.4`
